/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidad.Ciudad;
import Negocio.ClientesNegocio;
import Negocio.IClientesNegocios;
import Persistencia.ClientesDAO;
import Persistencia.ConexionBD;
import Persistencia.IClientesDAO;
import Persistencia.IConexionBD;
import Persistencia.PersistenciaException;
import dtoCinepolis.ClientesDTO;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Oley
 */
public class AgregarClientes extends javax.swing.JFrame {

    private ClientesNegocio clienteNegocio;

    /**
     * Creates new form AñadirClientes
     */
    public AgregarClientes(IClientesDAO clientesDAO) {

        this.setResizable(false);
        IConexionBD conexionBD = new ConexionBD();
        IClientesDAO clienteDAO = new ClientesDAO(conexionBD);
        ClientesNegocio clienteNegocio = new ClientesNegocio(clienteDAO);
        initComponents();

//        initComponents();
//        this.setLocationRelativeTo(null);
//        this.setResizable(false);
//        IConexionBD conexionBD = new ConexionBD();
//        IClienteDAO clienteDAO = new ClienteDAO(conexionBD);
//        clienteNegocio = new ClienteNegocio(clienteDAO);
    }

    public AgregarClientes() {
    }

    private ClientesDTO crearClientesDTO() throws DateTimeParseException {
        String nombre = txtNombres.getText();
        String apellidoPaterno = txtApellidoPaterno.getText();
        String apellidoMaterno = txtApellidoMaterno.getText();
        String fechaNacimientoTexto = txtFechaNacimiento.getText();

        // Cambiar el formateador a solo manejar fechas
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate fechaNacimiento = LocalDate.parse(fechaNacimientoTexto, formatter);  // Cambiar a LocalDate

        String ciudad = txtCiudad.getText();
        String correo = txtCorreo.getText();
        String contraseña = txtContrasena.getText();

        ClientesDTO clientesDTO = new ClientesDTO();
        clientesDTO.setNombre(nombre);
        clientesDTO.setApellidoPaterno(apellidoPaterno);
        clientesDTO.setApellidoMaterno(apellidoMaterno);
        clientesDTO.setFechaNacimiento(fechaNacimiento); // Ahora es LocalDate
        // clientesDTO.setCiudad(ciudad); // Si quieres agregar la ciudad, descomenta esta línea
        clientesDTO.setCorreo(correo);
        clientesDTO.setContraseña(contraseña);

        return clientesDTO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Agregar Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 52, 260, 30));

        jLabel3.setText("Apellido Paterno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 102, 240, 30));

        jLabel4.setText("Apellido Materno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 240, 30));

        jLabel5.setText("Fecha Nacimiento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        getContentPane().add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 230, 30));

        jLabel6.setText("Ciudad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        getContentPane().add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 240, 30));

        jLabel7.setText("Correo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 282, 240, 30));

        jLabel8.setText("Contraseña:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));
        getContentPane().add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 322, 240, 30));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jButton2.setText("Continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String nombres = txtNombres.getText();
            String apellidoPaterno = txtApellidoPaterno.getText();
            String apellidoMaterno = txtApellidoMaterno.getText();

            // Obtener el texto del campo y definir el formato
            String fechaNacimientoTexto = txtFechaNacimiento.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            // Parsear el texto a LocalDate
            LocalDate fechaNacimiento = LocalDate.parse(fechaNacimientoTexto, formatter);

            String correo = txtCorreo.getText();
            String contrasena = txtContrasena.getText();
            String ciudad = txtCiudad.getText();
            
            if (nombres.equals("") || apellidoPaterno.equals("") || apellidoMaterno.equals("") || fechaNacimiento.equals("") || correo.equals("") || contrasena.equals("") || ciudad.equals(evt)) {
                JOptionPane.showMessageDialog(null, "Favor de rellenar campos");
            } else {
                Ciudad c = new Ciudad(nombres);
                ClientesDTO clienteDTO = new ClientesDTO(nombres, apellidoPaterno, apellidoMaterno, fechaNacimiento, correo, contrasena, c);
                
                try {
                    clienteNegocio.guardar(clienteDTO);
                    this.dispose();
                } catch (Exception e) {
                }
            }



//         try {
//        ClientesDTO clientesDTO = crearClientesDTO();
//        clientesNegocios.guardar(clientesDTO);
//        this.setVisible(false);
//        new ExitoCliente().setVisible(true);
//    } catch (DateTimeParseException e) {
//        JOptionPane.showMessageDialog(this, "Formato de fecha no válido: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    } catch (PersistenciaException ex) {
//        Logger.getLogger(AñadirClientes.class.getName()).log(Level.SEVERE, null, ex);
//        JOptionPane.showMessageDialog(this, "Error al guardar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
//    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
