/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Negocio.CiudadesNegocio;
import Negocio.NegocioException;
import Negocio.SalasNegocios;
import Negocio.SucursalesNegocio;
import Persistencia.ConexionBD;
import Persistencia.SalasDAO;
import Persistencia.SucursalDAO;
import dtoCinepolis.SalasDTO;
import dtoCinepolis.SucursalesDTO;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Oley
 */
public class AgregarSalas extends javax.swing.JFrame {

    private ConexionBD conexionBD;
    private SucursalesNegocio sucursalesNegocio;
    private SucursalDAO sucursalDAO;
    private SalasDAO salasDAO;
    private SalasNegocios salasNegocios;
    private CiudadesNegocio ciudadesNegocio;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    /**
     * Creates new form AgregarSalas
     */
    public AgregarSalas() {
        initComponents();
        conexionBD = new ConexionBD();
        sucursalDAO = new SucursalDAO(conexionBD);
        sucursalesNegocio = new SucursalesNegocio(sucursalDAO, ciudadesNegocio);
        salasDAO = new SalasDAO(conexionBD);
        salasNegocios = new SalasNegocios(salasDAO, sucursalesNegocio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Añadir Sala");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel2.setText("Nombre de la sala:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 350, -1));

        jLabel3.setText("Cantidad de asientos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, -1));

        jLabel4.setText("Tiempo de limpieza:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 350, -1));

        jLabel5.setText("Sucursal:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 350, -1));

        jButton1.setText("Añadir Sucursal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel6.setText("Costo sugerido:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 292, 350, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String nombreSala = jTextField1.getText();
            String nombreSucursal = jTextField4.getText();
            String minutosTexto = jTextField2.getText();
            double costoAproximado = Double.parseDouble(jTextField5.getText());
            if (nombreSala.isEmpty() || nombreSucursal.isEmpty() || minutosTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int cantidadAsientos = Integer.parseInt(jTextField2.getText());

            int minutosAAnadir = Integer.parseInt(minutosTexto);

            LocalDateTime fechaLimpieza = LocalDateTime.now().plusMinutes(minutosAAnadir);

            SalasDTO salasDTO = new SalasDTO();
            salasDTO.setNombre(nombreSala);
            salasDTO.setCantidadAsientos(cantidadAsientos);
            salasDTO.setTiempoLimpieza(fechaLimpieza);
            salasDTO.setCostoSugerido(costoAproximado);

            SucursalesDTO sucursalDTO = sucursalesNegocio.buscarSucursalPorNombre(nombreSucursal);
            if (sucursalDTO == null) {
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            salasDTO.setSucursales(sucursalDTO);

            salasNegocios.guardarSucursalesConSalas(salasDTO, nombreSucursal);

            JOptionPane.showMessageDialog(this, "Sala añadida exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            jTextField1.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
            this.setVisible(false);
            CatalogoSalas catalogoSalas=new CatalogoSalas();
            catalogoSalas.setVisible(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce un número válido en cantidad de asientos y minutos.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar la sala: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Se ha producido un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
