/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrativp;

import Negocio.CiudadesNegocio;
import Negocio.ICiudadesNegocio;
import Negocio.IFuncionesNegocio;
import Negocio.IPeliculasNegocio;
import Negocio.ISalasNegocios;
import Negocio.ISucursalesNegocio;
import Persistencia.PersistenciaException;
import dtoCinepolis.CiudadesDTO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Oley
 */
public class AgregarCiudades extends javax.swing.JFrame {

   private  ICiudadesNegocio ciudadesNegocio;
private ISucursalesNegocio sucursalesNeggocio;
private  ISalasNegocios salasNegocios;
private IPeliculasNegocio peliculasNegocio;
private IFuncionesNegocio funcionesNegocio;
    /**
     * Creates new form AñadirCiudades
     */
    public AgregarCiudades(ICiudadesNegocio ciudadesNegocio) {
        this.ciudadesNegocio = ciudadesNegocio;
        initComponents();
    }

    private void agregarCiudad() throws PersistenciaException {
     String nombre = jTextField1.getText().trim(); // Elimina espacios en blanco

        if (nombre.isEmpty()) {
            throw new PersistenciaException("El nombre de la ciudad no puede estar vacío.");
        }

        CiudadesDTO ciudadesDTO = new CiudadesDTO(nombre, false);
        ciudadesNegocio.guardar(ciudadesDTO);  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Añadir ciudad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel2.setText("Nombre de la ciudad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 260, -1));

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
            agregarCiudad();
            this.setVisible(false);
            ExitoCiudad exitoCiudad = new ExitoCiudad();
            exitoCiudad.setVisible(true);
        } catch (PersistenciaException ex) {
            Logger.getLogger(AgregarCiudades.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }









//        try {
//            agregarCiudad();
//        } catch (PersistenciaException ex) {
//            Logger.getLogger(AgregarCiudades.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        this.setVisible(false);
//        ExitoCiudad exitoCiudad = new ExitoCiudad();
//        exitoCiudad.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

this.setVisible(false);
        Amdministrador administrador=new Amdministrador(ciudadesNegocio,sucursalesNeggocio,salasNegocios,peliculasNegocio, funcionesNegocio);
administrador.setVisible(true);




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
