/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrativp;

import Negocio.ISalasNegocios;
import Negocio.ISucursalesNegocio;
import Negocio.NegocioException;
import dtoCinepolis.SalaFiltroTablaDTO;
import dtoCinepolis.SalasFiltroTablaDTO;
import dtoCinepolis.SalasTablaDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oley
 */
public class CatalogoSalas extends javax.swing.JFrame {

    private ISalasNegocios salasNegocios;
    private ISucursalesNegocio sucursalesNegocio;
    private int idSalasSeleccionada = -1;

    /**
     * Creates new form CatalogoSalas
     */
    public CatalogoSalas(ISalasNegocios salasNegocios, ISucursalesNegocio sucursalesNegocio) {
        this.sucursalesNegocio = sucursalesNegocio;
        this.salasNegocios = salasNegocios;
        initComponents();

        cargarTablaSalas();
        jTable1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    int row = jTable1.getSelectedRow();
                    if (row != -1) {
                        idSalasSeleccionada = (int) jTable1.getValueAt(row, 4);
                        System.out.println("ID Ciudad seleccionada: " + idSalasSeleccionada);
                    }
                }
            }
        });
    }

    private void abrirDetallesSalas(int idSalas) {
        DetallesSalas detallesSalas = new DetallesSalas(idSalas,salasNegocios, sucursalesNegocio);
        detallesSalas.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void AgregarRegistroTablaSalas(List<SalasTablaDTO> salasLista) {
        if (salasLista == null) {
            return;
        }
        DefaultTableModel modeloTabla = (DefaultTableModel) this.jTable1.getModel();
        salasLista.forEach(row -> {
            Object[] fila = new Object[5];
            fila[0] = row.getNombre();
            fila[1] = row.getCantidadAsientos();
            fila[2] = row.getTiempoLimpieza();
            fila[3] = row.getCantidadAsientos();
            fila[4]=row.getId();
            modeloTabla.addRow(fila);
        });
    }

    private void BorrarRegistroTablaSalas() {
        DefaultTableModel modeloTabla = (DefaultTableModel) this.jTable1.getModel();
        modeloTabla.setRowCount(0);
    }

    private int getIdSelecionadoTablaSalas() {
        int indiceFilasSelecionada = this.jTable1.getSelectedRow();
        if (indiceFilasSelecionada != -1) {
            DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();

            int indiceColumnaId = 0;
            int idSocioSeleccionado = (int) modelo.getValueAt(indiceFilasSelecionada,
                    indiceColumnaId);
            return idSocioSeleccionado;
        } else {
            return 0;
        }
    }

    private void cargarTablaSalas() {
        try {
            SalaFiltroTablaDTO filtroTablaDTO = obtenerFiltrosTablas();
            List<SalasTablaDTO> salasLista = salasNegocios.buscarSalaTabla(filtroTablaDTO);
            BorrarRegistroTablaSalas();
            AgregarRegistroTablaSalas(salasLista);
        } catch (NegocioException e) {
            BorrarRegistroTablaSalas();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Información", JOptionPane.ERROR_MESSAGE);

        }
    }

    private SalaFiltroTablaDTO obtenerFiltrosTablas() {
        return new SalaFiltroTablaDTO(10, 0, jTextField1.getText());
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel1.setText("ADMINISTRADOR SALAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 240, -1));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nombre", "Cantidad Asientos", "Tiempo limpieza", "costo sugerido", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 170));

        jButton3.setText("<--");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 20));

        jButton4.setText("-->");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jButton5.setText("Detalles");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel2.setText("Pica la Salas que quieres y despues pulsa el boton de detalles!!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);
        AgregarSalas agregarSalas = new AgregarSalas(sucursalesNegocio, salasNegocios);
        agregarSalas.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

//this.setVisible(false);
//MenuAdministrador menuAdministrador= new MenuAdministrador();
//menuAdministrador.setVisible(true);
//
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        cargarTablaSalas();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (idSalasSeleccionada != -1) {
            System.out.println("ID sala antes de abrir: " + idSalasSeleccionada);
            abrirDetallesSalas(idSalasSeleccionada);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una sala de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
