/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrativp;

import Negocio.CiudadesNegocio;
import Negocio.ICiudadesNegocio;
import Negocio.NegocioException;
import Persistencia.CiudadesDAO;
import Persistencia.ConexionBD;
import Presentacion.OpcionesCiudades;
import dtoCinepolis.CuidadFiltroTablaDTO;
import dtoCinepolis.CuidadTablaDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import enumerador.CiudadCRUDEnumerador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Oley
 */
public class CatalogoCiudades extends javax.swing.JFrame {

    private ICiudadesNegocio ciudadesNegocio;
private int idCiudadSeleccionada = -1;
    /**
     * Creates new form CatalogoCiudades
     */
    public CatalogoCiudades(ICiudadesNegocio ciudadesNegocio) {

          this.ciudadesNegocio = ciudadesNegocio; 
        initComponents();
                cargarTablaCiudades();
  jTable1.addMouseListener(new MouseAdapter() {
    public void mouseClicked(MouseEvent e) {
        if (e.getClickCount() == 1) { 
            int row = jTable1.getSelectedRow();
            if (row != -1) {
                idCiudadSeleccionada = (int) jTable1.getValueAt(row, 0); 
                System.out.println("ID Ciudad seleccionada: " + idCiudadSeleccionada);
                }
            
        }
    }
});
    }
    
 private void abrirDetallesCiudad(int idCiudad) {
        OpcionesCiudades opcionesCiudades = new OpcionesCiudades(idCiudad);
        opcionesCiudades.setVisible(true); 
    }

    private void AgregarRegistrosTablaCiudad(List<CuidadTablaDTO> cuidadLista) {
        if (cuidadLista == null) {
            return;
        }
        DefaultTableModel modeloTabla = (DefaultTableModel) this.jTable1.getModel();
        cuidadLista.forEach(row -> {
            Object[] fila = new Object[2];
            fila[0] = row.getId();
            fila[1] = row.getNombre();
            modeloTabla.addRow(fila);
                    });

        }
 private void BorrarRegistrosTablaCuidades() {
        DefaultTableModel modeloTabla = (DefaultTableModel) this.jTable1.getModel();
        modeloTabla.setRowCount(0);
            
        
    }
   private int getIdSeleccionadoTablaClientes() {
        int indiceFilaSeleccionada = this.jTable1.getSelectedRow();
        if (indiceFilaSeleccionada != -1) {
            DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
            int indiceColumnaId = 0;
            int idSocioSeleccionado = (int) modelo.getValueAt(indiceFilaSeleccionada,
                    indiceColumnaId);
            return idSocioSeleccionado;
        } else {
            return 0;
        }
    }
 
   
    private void cargarTablaCiudades() {
        try {
            CuidadFiltroTablaDTO filtro = obtenerFiltrosTabla();
            List<CuidadTablaDTO> cuidadLista = ciudadesNegocio.buscarCuidadTabla(filtro);
            BorrarRegistrosTablaCuidades();
            AgregarRegistrosTablaCiudad(cuidadLista);
        } catch (NegocioException e) {
            this.BorrarRegistrosTablaCuidades();
//            this.HEIGHT--;
//            this.establecerTituloPaginacion();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Información", JOptionPane.ERROR_MESSAGE);

        }
    }
//    private void editar(){
//int id=getIdSeleccionadoTablaCiudades();
//if(id!=0){
//    try{
//        CiudadesDTO ciudadesDTO= ciudadesNegocio.
//    }
//}
//    }
   
    private CuidadFiltroTablaDTO obtenerFiltrosTabla() {
 return new CuidadFiltroTablaDTO(10, 0, jTextField1.getText());    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 520, 240));

        jLabel1.setText("Catalogo de Ciudades");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 400, -1));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jButton4.setText("<--");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jButton5.setText("-->");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        jButton6.setText("Detalles");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jLabel2.setText("Pica la ciudad que quieres y despues pulsa el boton de detalles!!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        AgregarCiudades añadirCiudades = new AgregarCiudades(ciudadesNegocio);
        añadirCiudades.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.cargarTablaCiudades();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//  this.setVisible(false);
//        MenuAdministrador administrador=new MenuAdministrador();
//administrador.setVisible(true);
//

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  if (idCiudadSeleccionada != -1) {
    System.out.println("ID Ciudad antes de abrir: " + idCiudadSeleccionada); 
    if (idCiudadSeleccionada != -1) {
        abrirDetallesCiudad(idCiudadSeleccionada);
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una ciudad de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    

    }
  }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
