/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrativp;

import Negocio.ISalasNegocios;
import Negocio.ISucursalesNegocio;
import Negocio.NegocioException;
import javax.swing.JOptionPane;

/**
 *
 * @author Oley
 */
public class DetallesSalas extends javax.swing.JFrame {

    private int idSalas;
    private ISalasNegocios salasNegocios;
    private ISucursalesNegocio sucursalesNegocio;

    /**
     * Creates new form DetallesSalas
     */
    public DetallesSalas(int idSalas, ISalasNegocios salasNegocios, ISucursalesNegocio sucursalesNegocio) {
        this.idSalas = idSalas;
        this.salasNegocios = salasNegocios;
        this.sucursalesNegocio = sucursalesNegocio;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
ModificarSala modificarSala= new ModificarSala(idSalas,salasNegocios, sucursalesNegocio);
modificarSala.setVisible(true);




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    private int getIdSelecionadaSalas() {
        return this.idSalas;
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        int idSalasSelecionada = getIdSelecionadaSalas();
//        if (idSalasSelecionada != 0) {
//            try {
//                salasNegocios.eliminar(idSalasSelecionada);
//                JOptionPane.showMessageDialog(this, "sala eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
//
//            } catch (NegocioException e) {
//                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "No se encontró la sala para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
//
//        }
        int idSalasSelecionada = getIdSelecionadaSalas();
        if (idSalasSelecionada != 0) {
            int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar esta sala?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    salasNegocios.eliminar(idSalasSelecionada);
                    JOptionPane.showMessageDialog(this, "Sala eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    CatalogoSalas catalogoSalas=new CatalogoSalas(salasNegocios, sucursalesNegocio);
                    catalogoSalas.setVisible(true);
                } catch (NegocioException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la sala para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
